POST http://localhost:8080/api/users
Content-Type: application/json

{
  "firstName": "Jackson",
  "lastName": "Connor",
  "emailAddress": "jackson.connor@resistance.net"
}

###

POST http://localhost:8080/api/users
Content-Type: application/json

{
  "firstName": "Richard",
  "lastName": "Johnson",
  "emailAddress": "richard.johnson@suckit.com"
}

###

GET http://localhost:8080/api/users/666

###

GET http://localhost:8080/api/users?lastNameFragment=Con
Accept: application/json
