POST http://localhost:8080/api/users
Content-Type: application/json

{
  "firstName": "Jackson",
  "lastName": "Connor",
  "emailAddress": "jackson.connor@resistance.net"
}

###

POST http://localhost:8080/api/users
Content-Type: application/json

{
  "firstName": "Richard",
  "lastName": "Johnson",
  "emailAddress": "richard.johnson@suckit.com"
}

###

GET http://localhost:8080/api/users/2

###

GET http://localhost:8080/api/users?lastNameFragment=johnson
Accept: application/json

###

POST http://localhost:8080/api/products
Content-Type: application/json

{
  "name": "12 Bad Men",
  "description": "Classical American cinema",
  "price": {
    "number": "19.99",
    "currency": "USD"
  },
  "type": "Video"
}
