POST http://localhost:8080/api/users
Content-Type: application/json

{
  "firstName": "Mitch",
  "lastName": "Buchanan",
  "emailAddress": "mitch.buchanan@baywatch.org"
}

###

POST http://localhost:8080/api/users
Content-Type: application/json

{
  "firstName": "Stacy",
  "lastName": "Sanchez",
  "emailAddress": "stacy.sanchez@baywatch.org"
}

###

GET http://localhost:8080/api/users/1
Accept: application/json

###

GET http://localhost:8080/api/users?lastNameFragment
Accept: application/json

###

POST http://localhost:8080/api/products
Content-Type: application/json

{
  "name": "20 Swell Dildos",
  "description": "Sex toys for the masses",
  "price": "99.99 USD",
  "type": "MUSIC"
}

###

POST http://localhost:8080/api/products
Content-Type: application/json

{
  "name": "14 Bad Men",
  "description": "Ancient American Cinema",
  "price": "19.99 USD",
  "type": "VIDEO"
}

###

PUT http://localhost:8080/api/products/1
Content-Type: application/json

{
  "name": "21 Bad Men",
  "description": "Modern Belgian Cinema",
  "price": "29.99 USD",
  "type": "VIDEO"
}

###

DELETE http://localhost:8080/api/products/1
Accept: application/json

###

GET http://localhost:8080/api/products
Accept: application/json

###

POST http://localhost:8080/api/orders
Content-Type: application/json

{
  "products": [
    {
      "id": 1
    },
    {
      "id": 2
    }
  ]
}

###

GET http://localhost:8080/api/orders/3
Accept: application/json

###


POST http://localhost:8080/api/products/1/files
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="pom.xml"

< ./pom.xml
--WebAppBoundary--

### testing remote component access

GET http://localhost:8080/api/exchange-rate?value=0%20USD
Accept: application/json

###

POST http://localhost:8080/api/messages
Content-Type: text/plain

What's up?
