POST http://localhost:8080/api/users
Content-Type: application/json

{
  "firstName": "Jackson",
  "lastName": "Connor",
  "emailAddress": "jackson.connor@resistance.net"
}

###

POST http://localhost:8080/api/users
Content-Type: application/json

{
  "firstName": "Richard",
  "lastName": "Johnson",
  "emailAddress": "richard.johnson@suckit.com"
}

###

GET http://localhost:8080/api/users/1
Accept: application/json

###

GET http://localhost:8080/api/users?lastNameFragment=johnson
Accept: application/json

###

POST http://localhost:8080/api/products
Content-Type: application/json

{
  "name": "12 Bad Men",
  "description": "Classical American cinema",
  "price": {
    "number": "19.99",
    "currency": "USD"
  },
  "type": "Video"
}

%%%

# Duration: 27 ms
# URL: http://localhost:8080/api/users

# HTTP/1.1 500

@Content-Type: application/json
@Transfer-Encoding: chunked
@Date: Thu, 23 Jul 2020 21:24:44 GMT
@Connection: close

{
  "description": "HttpMediaTypeNotSupportedException"
}