spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  servlet:
    multipart:
      location: ${java.io.tmpdir}
      enabled: true
      max-request-size: 5MB
      max-file size: 5MB
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:./shop
  messages:
    basename: messages #default value
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  mail:
    host: smtp.gmail.com
    port: 587
    username: adiforka@gmail.com
    password: .an.aT83..
    #password encoding
    tls: true
    properties.mail.stmp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com
apiPrefix: api
emailSender: adiforka@gmail.com
availableLanguages: en
defaultLanguage: en




